// <auto-generated />
namespace DatabaseMigration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Named_Entity_Added_IndexAdded_For_EnuqueName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Named_Entity_Added_IndexAdded_For_EnuqueName));
        
        string IMigrationMetadata.Id
        {
            get { return "201902240752314_Named_Entity_Added_IndexAdded_For_EnuqueName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
